In [1]:
import numpy as np

In [18]:
#Creating NumPy Array(1D)
a = np.array([1, 2, 3]) #To change the datatype of numpy array a = np.array([1, 2, 3], dtype = 'int16') by default it is int32
print(a)

[1 2 3]


In [5]:
#Creating NumPy Array(2D)
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
#ndim - number of dimensions(get dimension)
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#shape - number of rows and columns(get shape)
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [19]:
#dtype - the datatype of elements in the numpy array
a.dtype

dtype('int32')

In [12]:
print(b.dtype)

float64


In [20]:
a.itemsize #Size of each item in numpy array

4

In [21]:
a.size #Total number of elements

3

In [27]:
a.size * a.itemsize #Total size of the numpy array

12

In [28]:
a.nbytes #Same as above - number of bytes

12

In [30]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
a.shape

(2, 7)

In [32]:
#Get a specific element arrayname[rowindex, columnindex]
a[1, 5]

13

In [33]:
a[1, -2]

13

In [34]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
#Get a specific column
a[: , 2]

array([ 3, 10])

In [36]:
a[0, 1:6:2]

array([2, 4, 6])

In [37]:
a[0, 1:-1:2]

array([2, 4, 6])

In [39]:
#Changing an element in a numpyarray
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [40]:
a[: , 2] = 5

In [41]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [42]:
a[:, 2] = [1, 2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [43]:
#Creating a 3D array
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
#To get a specific element, work from outside to inside
b[0, 1, 1]

4

In [45]:
np.zeros(5) #Shape as argument

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [52]:
#full(shape, value)
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

In [53]:
#full_like(array, value) to use the shape of an existing numpy array
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [55]:
np.random.rand(2, 4)

array([[0.46329993, 0.54706281, 0.84895133, 0.51254381],
       [0.36637956, 0.84129775, 0.182306  , 0.20681705]])

In [56]:
np.random.random_sample(a.shape)

array([[0.86236959, 0.10064294, 0.62008359, 0.01677928, 0.16274671,
        0.14739578, 0.80697963],
       [0.3093461 , 0.82629424, 0.91595534, 0.20003011, 0.26920797,
        0.69796939, 0.67626079]])

In [57]:
np.random.randint(7, size = (3, 3))

array([[3, 5, 3],
       [0, 4, 2],
       [2, 4, 6]])

In [58]:
np.random.randint(2, 7, size = (3, 3))

array([[3, 5, 5],
       [3, 3, 5],
       [4, 4, 5]])

In [59]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
#Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [62]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [63]:
b = a #Not copy but b is point to the same elements as a does
print(b)

[1 2 3]


In [64]:
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [65]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a, b)

[1 2 3] [100   2   3]


In [66]:
a[0] = 200
print(a, b)

[200   2   3] [100   2   3]


In [67]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [68]:
a + 2

array([3, 4, 5, 6])

In [69]:
print(a)

[1 2 3 4]


In [70]:
print(a)
a += 2
print(a)

[1 2 3 4]
[3 4 5 6]


In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)

[5 7 9]


In [72]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [74]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [75]:
b = np.full((3, 2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [76]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [77]:
c = np.identity(3)
np.linalg.det(c) #Determinant

1.0

In [79]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [80]:
np.min(stats)

1

In [81]:
np.max(stats)

6

In [82]:
#axis = 1 row and axis = 0 column based
np.min(stats, axis = 1)

array([1, 4])

In [84]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [85]:
np.sum(stats)


21

In [87]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
after = before.reshape(2, 4)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [88]:
before.reshape(8, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [90]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
np.vstack([v1, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [94]:
h1 = np.zeros([2, 2])
h2 = np.ones([2, 2])
print(h1)
print(h2)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [95]:
np.hstack([h1, h2])

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [98]:
filedata = np.genfromtxt('numbers.txt', delimiter = ', ')
print(filedata)
filedata.astype('int32')

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [99]:
filedata > 50

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [100]:
filedata > 4

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [101]:
filedata[filedata > 4]

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [102]:
np.any(filedata > 4, axis = 0)

array([ True,  True,  True,  True,  True])

In [103]:
((filedata > 2) & (filedata < 6))

array([[False, False,  True,  True,  True],
       [False, False, False, False, False]])

In [104]:
(~(filedata > 2) & (filedata < 6))

array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

In [107]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [108]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,20,21,22]])
b = np.array([10,20,30,40])
a+b

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 40, 51, 62]])

In [109]:
a = np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
a[-3:-1,-4]


array([11, 15])